const FLATS_RECORD_FIELDS = {
    market: 'market',
    offerId: 'offerId',
    offerIdExpected: 'offerIdExpected',
    offerType: 'offerType',
    offerStatus: 'offerStatus',
    dateAdded: 'dateAdded',
    dateUpdated: 'dateUpdated',
    dateEndTransaction: 'dateEndTransaction',
    localization: 'localization',
    street: 'street',
    lawStatus: 'lawStatus',
    price: 'price',
    priceOffer: 'priceOffer',
    rent: 'rent',
    priceM2: 'priceM2',
    livingArea: 'livingArea',
    material: 'material',
    buildingType: 'buildingType',
    yearBuilt: 'yearBuilt',
    floorsNumber: 'floorsNumber',
    buildingQuality: 'buildingQuality',
    flatQuality: 'flatQuality',
    floor: 'floor',
    balcony: 'balcony',
    balconyQuantity: 'balconyQuantity',
    terracesQuantity: 'terracesQuantity',
    loggiasQuantity: 'loggiasQuantity',
    frenchBalconyQuantity: 'frenchBalconyQuantity',
    roomsNumber: 'roomsNumber',
    kitchenType: 'kitchenType',
    basement: 'basement',
    storageRoom: 'storageRoom',
    attic: 'attic',
    parkingPlace: 'parkingPlace',
    priceParkingUnderground: 'priceParkingUnderground',
    priceParkingGround: 'priceParkingGround',
    garden: 'garden',
    elevator: 'elevator',
    security: 'security',
    monitoring: 'monitoring',
    guardedArea: 'guardedArea',
    securityControl: 'securityControl',
    description: 'description'
}

module.exports = FLATS_RECORD_FIELDS;
