const FLATS_RECORD_FIELDS = {
    market: 'market',
    offerId: 'offerId',
    offerIdExpected: 'offerIdExpected',
    offerType: 'offerType',
    offerStatus: 'offerStatus',
    dateAdded: 'dateAdded',
    dateUpdated: 'dateUpdated',
    dateEndTransaction: 'dateEndTransaction',
    localization: 'localization',
    street: 'street',
    lawStatus: 'lawStatus',
    price: 'price',
    priceOffer: 'priceOffer',
    rent: 'rent',
    priceM2: 'priceM2',
    livingArea: 'livingArea',
    material: 'material',
    buildingType: 'buildingType',
    yearBuilt: 'yearBuilt',
    floorsNumber: 'floorsNumber',
    buildingQuality: 'buildingQuality',
    flatQuality: 'flatQuality',
    floor: 'floor',
    balcony: 'balcony',
    balconyQuantity: 'balconyQuantity',
    terracesQuantity: 'terracesQuantity',
    loggiasQuantity: 'loggiasQuantity',
    frenchBalconyQuantity: 'frenchBalconyQuantity',
    roomsNumber: 'roomsNumber',
    kitchenType: 'kitchenType',
    basement: 'basement',
    storageRoom: 'storageRoom',
    attic: 'attic',
    parkingPlace: 'parkingPlace',
    priceParkingUnderground: 'priceParkingUnderground',
    priceParkingGround: 'priceParkingGround',
    garden: 'garden',
    elevator: 'elevator',
    security: 'security',
    monitoring: 'monitoring',
    guardedArea: 'guardedArea',
    securityControl: 'securityControl',
    description: 'description',

    balconyDesc: 'balconyDesc',
    frenchBalconyDesc: 'frenchBalconyDesc',
    terraceDesc: 'terraceDesc',
    elevatorDesc: 'elevatorDesc',
    basementDesc: 'basementDesc',
    storageroomDesc: 'storageroomDesc',
    atticDesc: 'atticDesc',
    utilityroomDesc: 'utilityroomDesc',
    parkingSpaceDesc: 'parkingSpaceDesc',
    parkingPlaceDesc: 'parkingPlaceDesc',
    garageDesc: 'garageDesc',
    belongingDesc: 'belongingDesc',
    possibilityDesc: 'possibilityDesc',
    gardenDesc: 'gardenDesc',
    gardenDesc2: 'gardenDesc2',
    gardenDesc3: 'gardenDesc3',
    modernizatedBuildingDesc: 'modernizatedBuildingDesc',
    restoredBuildingDesc: 'restoredBuildingDesc',
    renewedBuildingDesc: 'renewedBuildingDesc',
    insulatedBuildingDesc: 'insulatedBuildingDesc',
    insulatedBuildingDesc2: 'insulatedBuildingDesc2',
    renovationDesc: 'renovationDesc',
    elevationDesc: 'elevationDesc',
    supervisionDesc: 'supervisionDesc',
    supervisionDesc2: 'supervisionDesc2',
    monitoringDesc: 'monitoringDesc',
    monitoringDesc2: 'monitoringDesc2',
    securityDesc: 'securityDesc',
    alarmDesc: 'alarmDesc',
    guardedDesc: 'guardedDesc',
    doorkeeperDesc: 'doorkeeperDesc',
    communityFlatDesc: 'communityFlatDesc',
    cooperativeflatDesc: 'cooperativeflatDesc',
    kitchenDesc: 'kitchenDesc',
    kitchenAnnexDesc: 'kitchenAnnexDesc',
    kitchenBrightDesc: 'kitchenBrightDesc',
    kitchenDarkDesc: 'kitchenDarkDesc',
    kitchenClearanceDesc: 'kitchenClearanceDesc',
    kitchenWindowDesc: 'kitchenWindowDesc',
    kitchenDiningRoomDesc: 'kitchenDiningRoomDesc',
    outbuildingDesc: 'outbuildingDesc',
    outbuildingDesc2: 'outbuildingDesc2',
    outbuildingDesc3: 'outbuildingDesc3',
    feesDesc: 'feesDesc',
    withoutRentDesc: 'withoutRentDesc',
    rentDesc: 'rentDesc',
    levelDesc: 'levelDesc'
}

const FLATS_RECORD_FIELDS_ANS = {
    technologyAns: 'technologyAns',
    lawStatusAns: 'lawStatusAns',
    elevatorAns: 'elevatorAns',
    basementAns: 'basementAns',
    garageAns: 'garageAns',
    gardenAns: 'gardenAns',
    modernizationAns: 'modernizationAns',
    alarmAns: 'alarmAns',
    kitchenAns: 'kitchenAns',
    outbuildingAns: 'outbuildingAns',
    qualityAns: 'qualityAns',
    rentAns: 'rentAns',
    commentsAns: 'commentsAns',
    deleteAns: 'deleteAns',
    rateStatus: 'rateStatus',
    user: 'user',
    updateDate: 'updateDate',

}

const FLATS_RECORD_SHORT_ANS = {
    flatId:'flatId',
    technologyShortAns:'technologyShortAns',
    elevatorShortAns:'elevatorShortAns',
    basementShortAns:'basementShortAns',
    garageShortAns:'garageShortAns',
    gardenShortAns:'gardenShortAns',
    modernizationShortAns:'modernizationShortAns',
    alarmShortAns:'alarmShortAns',
    kitchenShortAns:'kitchenShortAns',
    outbuildingShortAns:'outbuildingShortAns',
    qualityShortAns:'qualityShortAns',
    commentsShortAns:'commentsShortAns',
    updateDate:'updateDate',
}

module.exports = {
    FLATS_RECORD_FIELDS,
    FLATS_RECORD_FIELDS_ANS,
};
