const HOUSES_RECORD_FIELDS = {
    id: 'id',
    number: 'number',
    market: 'market',
    offerId: 'offerId',
    offerIdExpected: 'offerIdExpected',
    offerType: 'offerType',
    offerStatus: 'offerStatus',
    dateAdded: 'dateAdded',
    dateChanged: 'dateChanged',
    dateUpdated: 'dateUpdated',
    dateEndTransaction: 'dateEndTransaction',
    localization: 'localization',
    street: 'street',
    lawStatus: 'lawStatus',
    price: 'price',
    livingArea: 'livingArea',
    houseArea: 'houseArea',
    plotArea: 'plotArea',
    houseQuality: 'houseQuality',
    priceM2: 'priceM2',
    houseType: 'houseType',
    buildingQuality: 'buildingQuality',
    material: 'material',
    yearBuilt: 'yearBuilt',
    parkingPlace: 'parkingPlace',
    floorsNumber: 'floorsNumber',
    garagesNumber: 'garagesNumber',
    roomsNumber: 'roomsNumber',
    kitchenType: 'kitchenType',
    bathsNumber: 'bathsNumber',
    basement: 'basement',
    lotShape: 'lotShape',
    garden: 'garden',
    fence: 'fence',
    monitoring: 'monitoring',
    security: 'security',
    guardedArea: 'guardedArea',
    guardedEstate: 'guardedEstate',
    securityControl: 'securityControl',
    description: 'description',
    parkingSpaceDesc: 'parkingSpaceDesc',
    parkingPlaceDesc: 'parkingPlaceDesc',
    garageDesc: 'garageDesc',
    belongingDesc: 'belongingDesc',
    possibilityDesc: 'possibilityDesc',
    plotDesc: 'plotDesc',
    lawStatus1aDesc: 'lawStatus1aDesc',
    lawStatus2aDesc: 'lawStatus2aDesc',
    lawStatus3aDesc: 'lawStatus3aDesc',
    lawStatus4aDesc: 'lawStatus4aDesc',
    insulatedBuildingDesc: 'insulatedBuildingDesc',
    insulatedBuildingDesc2: 'insulatedBuildingDesc2',
    modernizatedBuildingDesc: 'modernizatedBuildingDesc',
    restoredBuildingDesc: 'restoredBuildingDesc',
    renewedBuildingDesc: 'renewedBuildingDesc',
    renovationDesc: 'renovationDesc',
    elevationDesc: 'elevationDesc',
    supervisionDesc: 'supervisionDesc',
    supervisionDesc2: 'supervisionDesc2',
    monitoringDesc: 'monitoringDesc',
    monitoringDesc2: 'monitoringDesc2',
    securityDesc: 'securityDesc',
    alarmDesc: 'alarmDesc',
    guardedDesc: 'guardedDesc',
    doorkeeperDesc: 'doorkeeperDesc',
    kitchenDesc: 'kitchenDesc',
    kitchenAnnexDesc: 'kitchenAnnexDesc',
    kitchenBrightDesc: 'kitchenBrightDesc',
    kitchenDarkDesc: 'kitchenDarkDesc',
    kitchenClearanceDesc: 'kitchenClearanceDesc',
    kitchenWindowDesc: 'kitchenWindowDesc',
    kitchenDiningRoomDesc: 'kitchenDiningRoomDesc',
    street1Desc: 'street1Desc',
    street2Desc: 'street2Desc',
    toilets1Desc: 'toilets1Desc',
    toilets2Desc: 'toilets2Desc',
    toilets3Desc: 'toilets3Desc',
    buildingType1Desc: 'buildingType1Desc',
    buildingType2Desc: 'buildingType2Desc',
    buildingType3Desc: 'buildingType3Desc',
    buildingType4Desc: 'buildingType4Desc',
    buildingType5Desc: 'buildingType5Desc',
    buildingType6Desc: 'buildingType6Desc',
    buildingType7Desc: 'buildingType7Desc',
}

const HOUSES_RECORD_FIELDS_ANS = {
    houseId: 'houseId',
    technologyAns: 'technologyAns',
    lawStatusAns: 'lawStatusAns',
    houseTypeAns: 'houseTypeAns',
    garageAns: 'garageAns',
    modernizationAns: 'modernizationAns',
    alarmAns: 'alarmAns',
    kitchenAns: 'kitchenAns',
    bathNumberAns: 'bathNumberAns',
    commentsAns: 'commentsAns',
    qualityAns: 'qualityAns',
    deleteAns:'deleteAns',
    rateStatus:'rateStatus',
    user:'user',
    updateDate:'updateDate',
}

const HOUSES_RECORD_SHORT_ANS = {
    houseId: 'houseId',
    technologyShortAns: 'technologyShortAns',
    lawStatusShortAns:'lawStatusShortAns',
    houseTypeShortAns:'houseTypeShortAns',
    garageShortAns:'garageShortAns',
    modernizationShortAns:'modernizationShortAns',
    alarmShortAns:'alarmShortAns',
    kitchenShortAns:'kitchenShortAns',
    bathNumberShortAns:'bathNumberShortAns',
    commentsShortAns:'commentsShortAns',
    qualityShortAns:'qualityShortAns',
    updateDate:'updateDate',
}

module.exports = {
    HOUSES_RECORD_FIELDS,
    HOUSES_RECORD_FIELDS_ANS,
    HOUSES_RECORD_SHORT_ANS,
}
