export const PLOTS_RECORD_FIELDS: { [key: string]: string } = {
    id: 'id',
    number: 'number',
    user: 'user',
    updateDate: 'updateDate',
    market: 'market',
    offerId: 'offerId',
    offerIdExpected: 'offerIdExpected',
    offerType: 'offerType',
    offerStatus: 'offerStatus',
    dateAdded: 'dateAdded',
    dateChanged: 'dateChanged',
    dateUpdated: 'dateUpdated',
    dateEndTransaction: 'dateEndTransaction',
    localization: 'localization',
    street: 'street',
    lawStatus: 'lawStatus',
    price: 'price',
    priceSold: 'priceSold',
    plotArea: 'plotArea',
    priceM2: 'priceM2',
    electricity: 'electricity',
    water: 'water',
    gas: 'gas',
    sewers: 'sewers',
    buildingConditions: 'buildingConditions',
    buildingPermit: 'buildingPermit',
    localPlan: 'localPlan',
    plotPurpose: 'plotPurpose',
    plotPurposeInPlan: 'plotPurposeInPlan',
    accessRoad: 'accessRoad',
    lotShape: 'lotShape',
    waterIntake: 'waterIntake',
    sewageType: 'sewageType',
    fence: 'fence',
    buildingOnPlot: 'buildingOnPlot',
    plotWidth: 'plotWidth',
    plotLength: 'plotLength',
    description: 'description',
    buildingType1Desc: 'buildingType1Desc',
    buildingType2Desc: 'buildingType2Desc',
    buildingType3Desc: 'buildingType3Desc',
    buildingType4Desc: 'buildingType4Desc',
    buildingType5Desc: 'buildingType5Desc',
    buildingType6Desc: 'buildingType6Desc',
    commercialPlotDesc: 'commercialPlotDesc',
    tradePlotDesc: 'tradePlotDesc',
    servicesPlotDesc: 'servicesPlotDesc',
    warehousePlotDesc: 'warehousePlotDesc',
    productionPlotDesc: 'productionPlotDesc',
    industryPlotDesc: 'industryPlotDesc',
    investmentPlotDesc: 'investmentPlotDesc',
    accompanyingPlotDesc: 'accompanyingPlotDesc',
    notBurdenPlotDesc: 'notBurdenPlotDesc',
    electricityDesc: 'electricityDesc',
    energyDesc: 'energyDesc',
    electricDesc: 'electricDesc',
    zkDesc: 'zkDesc',
    gasDesc: 'gasDesc',
    waterDesc: 'waterDesc',
    water2Desc: 'water2Desc',
    water3Desc: 'water3Desc',
    sewersDesc: 'sewersDesc',
    armedDesc: 'armedDesc',
    septictankDesc: 'septictankDesc',
    accessRoad1Desc: 'accessRoad1Desc',
    inRoadDesc: 'inRoadDesc',
    inBorderDesc: 'inBorderDesc',
    inPlotDesc: 'inPlotDesc',
    houseDesc: 'houseDesc',
    buildingDesc: 'buildingDesc',
    dismantlingDesc: 'dismantlingDesc',
    accessRoad2Desc: 'accessRoad2Desc',
    accessRoad3Desc: 'accessRoad3Desc',
    accessRoad4Desc: 'accessRoad4Desc',
    accessRoad5Desc: 'accessRoad5Desc',
    accessRoad6Desc: 'accessRoad6Desc',
    accessRoad7Desc: 'accessRoad7Desc',
    accessRoad8Desc: 'accessRoad8Desc',
    accessRoad9Desc: 'accessRoad9Desc',
    accessRoad10Desc: 'accessRoad10Desc',
    accessRoad11Desc: 'accessRoad11Desc',
    lawStatus4aDesc: 'lawStatus4aDesc',
    law1Desc: 'law1Desc',
    law2Desc: 'law2Desc',
    fencedArea1Desc: 'fencedArea1Desc',
    fencedArea2Desc: 'fencedArea2Desc',
    lotShape1Desc: 'lotShape1Desc',
    lotShape2Desc: 'lotShape2Desc',
    lotShape3Desc: 'lotShape3Desc',
    lotShape4Desc: 'lotShape4Desc',
    lotShape5Desc: 'lotShape5Desc',
    lotShape6Desc: 'lotShape6Desc',
    lotShape7Desc: 'lotShape7Desc',
    lotShape8Desc: 'lotShape8Desc',
    lawStatus1Desc: 'lawStatus1Desc',
    lawStatus2Desc: 'lawStatus2Desc',
    lawStatus3Desc: 'lawStatus3Desc',
    lawStatus4Desc: 'lawStatus4Desc',
    lawStatus5Desc: 'lawStatus5Desc',
    buildingType7Desc: 'buildingType7Desc',
    allowanceDesc: 'allowanceDesc',
}

export const PLOTS_RECORD_FIELDS_ANS: { [key: string]: string } = {
    plotId: 'plotId',
    documentAns: 'documentAns',
    plotPurposeAns: 'plotPurposeAns',
    plotPurposeJrAns: 'plotPurposeJrAns',
    plotPurposeWrAns: 'plotPurposeWrAns',
    plotPurposeJwrAns: 'plotPurposeJwrAns',
    plotPurposeFmtAns: 'plotPurposeFmtAns',
    houseTypeAns: 'houseTypeAns',
    lotShapeAns: 'lotShapeAns',
    waterAns: 'waterAns',
    gasAns: 'gasAns',
    sewersAns: 'sewersAns',
    electricityAns: 'electricityAns',
    isBuildingOnPlotAns: 'isBuildingOnPlotAns',
    accessRoadAns: 'accessRoadAns',
    buildingOnPlotAns: 'buildingOnPlotAns',
    fenceAns: 'fenceAns',
    commentsAns: 'commentsAns',
    deleteAns: 'deleteAns',
    rateStatus: 'rateStatus',
}

export const PLOTS_RECORD_SHORT_ANS = {
    plotId: 'plotId',
    documentShortAns: 'documentShortAns',
    plotPurposeShortAns: 'plotPurposeShortAns',
    plotPurposeJrShortAns: 'plotPurposeJrShortAns',
    plotPurposeWrShortAns: 'plotPurposeWrShortAns',
    plotPurposeJwrShortAns: 'plotPurposeJwrShortAns',
    plotPurposeFmtShortAns: 'plotPurposeFmtShortAns',
    houseTypeShortAns: 'houseTypeShortAns',
    lotShapeShortAns: 'lotShapeShortAns',
    waterShortAns: 'waterShortAns',
    gasShortAns: 'gasShortAns',
    sewersShortAns: 'sewersShortAns',
    electricityShortAnsTINYINT: 'electricityShortAnsTINYINT',
    isBuildingOnPlotShortAns: 'isBuildingOnPlotShortAns',
    accessRoadShortAns: 'accessRoadShortAns',
    buildingOnPlotShortAns: 'buildingOnPlotShortAns',
    fenceShortAns: 'fenceShortAns',
    commentsShortAns:'commentsShortAns',
    updateDate:'updateDate',
}

export const PLOTS_RECORD_GPT: { [key: string]: string } = {
    plotId:'plotId',
    documentGPT:'documentGPT',
    plotPurposeGPT:'plotPurposeGPT',
    plotPurposeJrGPT:'plotPurposeJrGPT',
    plotPurposeWrGPT:'plotPurposeWrGPT',
    plotPurposeJwrGPT:'plotPurposeJwrGPT',
    plotPurposeFmtGPT:'plotPurposeFmtGPT',
    houseTypeGPT:'houseTypeGPT',
    lotShapeGPT:'lotShapeGPT',
    waterGPT:'waterGPT',
    gasGPT:'gasGPT',
    sewersGPT:'sewersGPT',
    electricityAns:'electricityAns',
    isBuildingOnPlotGPT:'isBuildingOnPlotGPT',
    accessRoadGPT:'accessRoadGPT',
    buildingOnPlotGPT:'buildingOnPlotGPT',
    fenceGPT:'fenceGPT',
    updateDate:'updateDate',
}

export const argsAns = [
    "plotId", "documentAns", "plotPurposeAns", "plotPurposeJrAns", "plotPurposeWrAns",
    "plotPurposeJwrAns", "plotPurposeFmtAns", "houseTypeAns", "lotShapeAns", "waterAns",
    "gasAns", "sewersAns", "isBuildingOnPlotAns", "accessRoadAns", "buildingOnPlotAns",
    "fenceAns", "commentsAns", "deleteAns", "rateStatus", "user"
];

export const argsPartialAns = [
    "plotId", "lotShapeAns", "isBuildingOnPlotAns", "accessRoadAns", "buildingOnPlotAns",
    "fenceAns", "commentsAns", "user"
];

export const argsGPT = [
    "plotId", "documentGPT", "document_summary", "plotPurposeGPT", "plotPurpose_summary", "plotPurposeJrGPT", "plotPurposeJr_summary",
    "plotPurposeWrGPT", "plotPurposeWr_summary", "plotPurposeJwrGPT", "plotPurposeJwr_summary", "plotPurposeFmtGPT", "plotPurposeFmt_summary",
    "houseTypeGPT", "houseType_summary", "lotShapeGPT", "lotShape_summary", "waterGPT", "water_summary", "gasGPT", "gas_summary",
    "sewersGPT", "sewers_summary", "electricityAns", "electricity_summary", "isBuildingOnPlotGPT", "isBuildingOnPlot_summary",
    "accessRoadGPT", "accessRoad_summary", "buildingOnPlotGPT", "buildingOnPlot_summary", "fenceGPT", "fance_summary", "status"
];